name: GitHub Pages Deployment

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build and deploy job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      # Create base directory structure
      - name: Setup site directory
        run: mkdir -p _site
      
      # Deploy TSV files using the composite action
      - name: Deploy TSV files
        uses: ./.github/actions/deploy-tsv
        with:
          output-dir: './_site'

      # Upload the generated site content
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

      # Deploy the site content to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4